#!/bin/bash
#
# check for any reported events
#

# include Nagios utilities
. /opt/local/libexec/nagios/utils.sh

ipmi_ip=$1

SEL_LIST=`/usr/sbin/ipmitool -I lan -H $ipmi_ip -U ipmi-user -f /opt/tools/var/ipmitool/ipmi sel list 2>/dev/null`
ASSERTED=`/usr/bin/echo $SEL_LIST | /usr/bin/grep 'Asserted'`
LINE_NO=`/usr/bin/echo $SEL_LIST | /usr/bin/grep 'Asserted' | /usr/bin/wc -l`

if [ $LINE_NO -ne 0 ]; then
  echo "IPMI SEL CRITICAL: '$ASSERTED'"
  exit $STATE_CRITICAL
else
  echo "IPMI SEL OK: no events found"
  exit $STATE_OK
fi
