#!/usr/bin/sh
#
# Nagios-Skript zum pruefen des Inhalts einer Webseite
#
# Parameter:
#   URL
#   Suchstring (regulaerer Ausdruck)
# check_website_content


START=$(date +%s.%N)
RESULT=$(/usr/bin/wget --no-check-certificate -O - "$1" 2>&1 | /usr/bin/grep "$2")
END=$(date +%s.%N)
DIFF=$( /usr/bin/echo "$END - $START" | /usr/bin/bc )
INT=$( /usr/bin/echo "$DIFF" | /usr/bin/awk '{printf "%.0f",$1}' )

if [ -z "$RESULT" ]; then
  /usr/bin/printf "CRITICAL Problem finding '$2' in '$1' (time: '$DIFF' seconds)\n" >&2
  STATUS=1
else
  if [ $INT -lt 2 ]; then
    /usr/bin/printf "OK Found '$2' in '$1' (time: $DIFF seconds)\n"
    STATUS=0
  else
    # 2 or more seconds load time!
    /usr/bin/printf "WARNING Found '$2' in '$1' but load time to high: $DIFF seconds\n" >&2
    STATUS=1
  fi
fi

exit $STATUS
